---
# Loads all servers into the playbook so their hosts file can be updated later
- hosts: all
  tasks: []
  roles:
    - updatehosts

- name: Install zookeeper nodes
  hosts: ZookeeperKafka
  become: no

  roles:
    - common
    - zookeeper
