- name: Add iptables
  yum:
    pkg={{item}} state=installed
  with_items:
    - iptables
    - iptables-services

- name: Iptables block incoming traffic on public device
  iptables:
    chain: INPUT
    action: insert
    in_interface: eth1
    ctstate: NEW
    jump: DROP

- name: Enable iptables
  service: 
    name: iptables 
    state: started
    enabled: yes

- name: Pause before starting spark master
  pause:
    seconds: 10

- name: start spark master
  shell: sbin/start-master.sh
  args:
    chdir: /opt/spark

- name: start thrift slave
  shell: sbin/start-slave.sh spark://localhost:7077
  args:
    chdir: /opt/spark

- name: copy in script
  copy:
    dest: /opt/hive.bsh
    content: |
      !connect jdbc:hive2://localhost:10000
      CREATE TABLE hashtag USING org.apache.spark.sql.cassandra OPTIONS (keyspace 'w251twitter', table 'hashtag');
      CREATE TABLE sentiment USING org.apache.spark.sql.cassandra OPTIONS (keyspace 'w251twitter', table 'sentiment');
      CREATE TABLE tweets USING org.apache.spark.sql.cassandra OPTIONS (keyspace 'w251twitter', table 'tweets');
      CREATE TABLE twitter_connections USING org.apache.spark.sql.cassandra OPTIONS (keyspace 'w251twitter', table 'twitter_connections');


- name: start thrift server
  shell: sbin/start-thriftserver.sh --packages com.datastax.spark:spark-cassandra-connector_2.11:2.3.0 --confspark.cassandra.connection.host=cassandra1,cassandra2,cassandra3 --master spark://localhost:7077
  args:
    chdir: /opt/spark

