  - name: Creates cassandra directory
    file: path=/var/lib/cassandra state=directory group=root owner=root

  - parted:
      device: /dev/xvdc
      number: 1
      state: present

  - name: Create a ext4 filesystem on /dev/xvdc1 and check disk blocks
    filesystem:
      fstype: ext4
      dev: /dev/xvdc1
  
  - name: Mount the disk
    mount:
      path: /var/lib/cassandra
      src: /dev/xvdc1
      fstype: ext4
      state: mounted

  - name: Add java
    yum:
      name: http://10.73.183.212/Cassandra/jre-8u181-linux-x64.rpm
      state: present

  - name: Add Cassandra
    yum:
      name: http://10.73.183.212/Cassandra/cassandra-3.11.2-1.noarch.rpm
      state: present

  - name: Add jemalloc
    yum:
      name: http://10.73.183.212/Cassandra/jemalloc-3.6.0-1.el7.x86_64.rpm
      state: present

  - name: Install numpy
    pip:
      name: pip,numpy,pandas
      executable: pip3.6

  - name: Set swappiness
    sysctl:
      name: vm.swappiness
      value: 10
      state: present

  - name: Set vm.max_map_count = 1048575
    sysctl:
      name: vm.max_map_count
      value: 1048575
      state: present

  - name: update cassandra config file
    template:
      src: cassandra.yaml.j2
      dest: /etc/cassandra/conf/cassandra.yaml

  - name: Enable cassandra service
    service: 
      name: cassandra
      enabled: yes

  - name: Start cassandra service
    service: 
      name: cassandra
      state: started
