---
# Loads all servers into the playbook so their hosts file can be updated later
- hosts: all
  tasks: []
  roles:
    - updatehosts

- name: Install Thrift nodes
  hosts: ThriftServers
  become: no

  roles:
    - common
    - thrift
