- name: Add Kafka
  unarchive:
    src: http://10.73.183.212/Kafka/kafka_2.11-0.8.2.2.tgz
    dest: /opt
    creates: /opt/kafka_2.11-0.8.2.2
    remote_src: yes

- name: Symbolic link to Kafka
  file:
    src: /opt/kafka_2.11-0.8.2.2
    dest: /opt/kafka
    state: link

- name: Set permissions to Kafka folder
  file: path=/opt/kafka/ owner=root group=root recurse=yes

- name: Set up kafka configuration
  template:
    src: server.properties.j2
    dest: /opt/kafka/config/server.properties

- name: pause for a few seconds before starting broker
  pause:
    seconds: 10

- name: Start kafka
  shell: sleep 10; /opt/kafka/bin/kafka-server-start.sh -daemon config/server.properties 1>/dev/null 2>&1 &
  args:
    chdir: /opt/kafka
